# Generated by Django 5.2.17 on 2026-10-06 10:49

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CampaignProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("offer", models.TextField()),
                (
                    "countries",
                    apps.core.fields.StringListField(
                        default=list, help_text="ISO 3166-1 alpha-2 codes, upper case, e.g. SA."
                    ),
                ),
                ("industries", apps.core.fields.StringListField(default=list)),
                ("company_size_min", models.PositiveIntegerField(blank=True, null=True)),
                ("company_size_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "business_model",
                    models.CharField(
                        choices=[("b2b", "B2B"), ("b2c", "B2C"), ("both", "B2B and B2C")],
                        default="b2b",
                        max_length=8,
                    ),
                ),
                ("excluded_industries", apps.core.fields.StringListField(default=list)),
                ("excluded_company_types", apps.core.fields.StringListField(default=list)),
                ("target_departments", apps.core.fields.StringListField(default=list)),
                (
                    "preferred_buyer_titles",
                    apps.core.fields.StringListField(
                        default=list, help_text="Ordered, first is most preferred."
                    ),
                ),
                (
                    "outreach_languages",
                    apps.core.fields.StringListField(
                        default=list, help_text="Language codes, lower case, e.g. en, ar."
                    ),
                ),
                (
                    "custom_rules",
                    models.TextField(blank=True, help_text="Free-form qualification notes."),
                ),
                (
                    "change_note",
                    models.TextField(blank=True, help_text="Why this version was made."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profiles",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("campaign_id", "-version"),
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="current_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="campaigns.campaignprofile",
            ),
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="campaignprofile",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                related_query_name="%(app_label)s_%(class)s",
                to="campaigns.client",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                related_query_name="%(app_label)s_%(class)s",
                to="campaigns.client",
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("archived_at__isnull", True)),
                name="campaigns_client_name_unique_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "archived"])),
                name="campaigns_client_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("archived_at__isnull", False), ("status", "archived")),
                    models.Q(
                        models.Q(("status", "archived"), _negated=True),
                        ("archived_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="campaigns_client_archived_matches_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignprofile",
            constraint=models.UniqueConstraint(
                fields=("campaign", "version"), name="campaigns_profile_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignprofile",
            constraint=models.UniqueConstraint(
                fields=("campaign", "id"), name="campaigns_profile_campaign_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="campaigns_profile_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("company_size_min__isnull", True),
                    ("company_size_max__isnull", True),
                    ("company_size_min__lte", models.F("company_size_max")),
                    _connector="OR",
                ),
                name="campaigns_profile_size_min_lte_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("business_model__in", ["b2b", "b2c", "both"])),
                name="campaigns_profile_business_model_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("offer", ""), _negated=True),
                name="campaigns_profile_offer_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                models.F("client"),
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("archived_at__isnull", True)),
                name="campaigns_campaign_name_unique_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "active", "archived"])),
                name="campaigns_campaign_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("archived_at__isnull", False), ("status", "archived")),
                    models.Q(
                        models.Q(("status", "archived"), _negated=True),
                        ("archived_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="campaigns_campaign_archived_matches_status",
            ),
        ),
    ]
