/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * API name, version and self link
     * @description Public entry point of the v1 API.
     */
    get: operations["api_root"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log in
     * @description Exchange email and password for an access and refresh token.
     *
     *     Every failure (unknown email, wrong password, inactive user) returns the same generic 401.
     */
    post: operations["auth_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log out (blacklist the refresh token)
     * @description Blacklist the refresh token (and clear the cookie). Access tokens expire on their own.
     */
    post: operations["auth_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Current user
     * @description The authenticated user.
     */
    get: operations["auth_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh the token pair
     * @description Rotate: returns a new access token and a new refresh token, blacklisting the old one.
     */
    post: operations["auth_refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/clients/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List clients
     * @description Clients the user is a member of (all clients for a global admin), paginated. Archived clients are hidden unless `archived`/`status` ask for them. Needs the `READ` level: any member. Others get 403; clients you are not a member of give 404.
     */
    get: operations["clients_list"];
    put?: never;
    /**
     * Create a client
     * @description Creates an active client; the creator becomes its admin member. Needs the `MANAGE` level in at least one client (or global admin): there is no client to check yet, so this is the platform-level rule. Name must be unique, ignoring case, among non-archived clients.
     */
    post: operations["clients_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/clients/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a client
     * @description Archived clients can be retrieved by id. Needs the `READ` level: any member. Others get 403; clients you are not a member of give 404.
     */
    get: operations["clients_retrieve"];
    /**
     * Replace a client's name and notes
     * @description An archived client is read-only (400). Needs the `EDIT` level: manager and admin. Others get 403; clients you are not a member of give 404.
     */
    put: operations["clients_update"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Edit a client's name and/or notes
     * @description An archived client is read-only (400). Needs the `EDIT` level: manager and admin. Others get 403; clients you are not a member of give 404.
     */
    patch: operations["clients_partial_update"];
    trace?: never;
  };
  "/api/v1/clients/{id}/archive/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Archive a client
     * @description Soft delete: the client leaves default lists, all its data is kept. Idempotent. Campaigns are not changed. Needs the `MANAGE` level: admin. Others get 403; clients you are not a member of give 404.
     */
    post: operations["clients_archive"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/clients/{id}/restore/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restore an archived client
     * @description 400 on `name` if another active client now uses the name. Needs the `MANAGE` level: admin. Others get 403; clients you are not a member of give 404.
     */
    post: operations["clients_restore"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness probe
     * @description Liveness: the process is serving requests. Touches no dependency.
     */
    get: operations["health_live"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness probe
     * @description Readiness: 200 when every check passes, otherwise 503 with the same JSON body.
     */
    get: operations["health_ready"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiLinks: {
      /**
       * Format: uri
       * @description Absolute URL of this endpoint.
       */
      self: string;
    };
    /** @description Body of `GET /api/v1/` (documentation only). */
    ApiRoot: {
      name: string;
      version: string;
      links: components["schemas"]["ApiLinks"];
    };
    /** @description One readiness check; the extra fields depend on the check (documentation only). */
    Check: {
      status: components["schemas"]["CheckStatusEnum"];
      /** @description Fixed explanation of a failure. */
      detail?: string;
      /** @description migrations: up to 10 unapplied migrations. */
      pending?: string[];
      /** @description migrations: total pending. */
      pending_count?: number;
      /** @description worker: live clusters. */
      clusters?: number;
      /**
       * Format: double
       * @description worker: age of the newest heartbeat.
       */
      heartbeat_age_seconds?: number;
    };
    /**
     * @description * `ok` - ok
     *     * `fail` - fail
     *     * `skipped` - skipped
     * @enum {string}
     */
    CheckStatusEnum: "ok" | "fail" | "skipped";
    /**
     * @description A client. ``status`` and the timestamps are read-only: use ``archive/`` and ``restore/``.
     *
     *     Name uniqueness (case-insensitive, among non-archived clients) is enforced by the service
     *     layer and reported as a ``name`` field error in the standard error envelope.
     */
    Client: {
      /** Format: uuid */
      readonly id: string;
      name: string;
      notes?: string;
      readonly status: components["schemas"]["ClientStatusEnum"];
      /** Format: date-time */
      readonly archived_at: string | null;
      /** Format: date-time */
      readonly created_at: string;
      /** Format: date-time */
      readonly updated_at: string;
    };
    /**
     * @description A client. ``status`` and the timestamps are read-only: use ``archive/`` and ``restore/``.
     *
     *     Name uniqueness (case-insensitive, among non-archived clients) is enforced by the service
     *     layer and reported as a ``name`` field error in the standard error envelope.
     */
    ClientRequest: {
      name: string;
      notes?: string;
    };
    /**
     * @description * `active` - Active
     *     * `archived` - Archived
     * @enum {string}
     */
    ClientStatusEnum: "active" | "archived";
    /** @description The `error` object of the standard envelope (apps/core/exceptions.py). */
    ErrorBody: {
      /** @description Stable machine-readable code, e.g. `validation_error`. */
      code: string;
      /** @description Human-readable summary; may change, do not parse. */
      message: string;
      /** @description Field errors for `validation_error`, `{retry_after}` for `throttled`, else null. */
      details: unknown;
      /** @description Value of the `X-Request-ID` response header. */
      request_id: string | null;
    };
    /** @description Every error response of the API has this body. */
    ErrorEnvelope: {
      error: components["schemas"]["ErrorBody"];
    };
    /** @description Body of `/healthz` (documentation only). */
    Health: {
      status: components["schemas"]["HealthStatusEnum"];
    };
    /**
     * @description * `ok` - ok
     * @enum {string}
     */
    HealthStatusEnum: "ok";
    PaginatedClientList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["Client"][];
    };
    /**
     * @description A client. ``status`` and the timestamps are read-only: use ``archive/`` and ``restore/``.
     *
     *     Name uniqueness (case-insensitive, among non-archived clients) is enforced by the service
     *     layer and reported as a ``name`` field error in the standard error envelope.
     */
    PatchedClientRequest: {
      name?: string;
      notes?: string;
    };
    /** @description Body of `/readyz`: 200 when `status` is `ok`, 503 when `unavailable`. */
    Readiness: {
      status: components["schemas"]["ReadinessStatusEnum"];
      /** @description Keyed by check: database, migrations, worker. */
      checks: {
        [key: string]: components["schemas"]["Check"];
      };
    };
    /**
     * @description * `ok` - ok
     *     * `unavailable` - unavailable
     * @enum {string}
     */
    ReadinessStatusEnum: "ok" | "unavailable";
    /** @description Body of `refresh/` and `logout/` (documentation only; the views read the raw body). */
    RefreshTokenRequest: {
      /** @description Refresh token. May be omitted when the refresh cookie is enabled. */
      refresh?: string;
    };
    TokenObtainPairRequest: {
      email: string;
      password: string;
    };
    /** @description Tokens returned by `login/` and `refresh/` (documentation only). */
    TokenResponse: {
      /** @description Short-lived JWT access token (Bearer). */
      access: string;
      /** @description Refresh token. Omitted when the refresh cookie is enabled (it is then delivered as an httpOnly cookie). */
      refresh?: string;
    };
    User: {
      /** Format: uuid */
      readonly id: string;
      /**
       * Email address
       * Format: email
       */
      readonly email: string;
      readonly name: string;
      /** @description Can sign in to the Django admin. */
      readonly is_staff: boolean;
      /** Format: date-time */
      readonly last_login: string | null;
      /** Format: date-time */
      readonly created_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  api_root: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiRoot"];
        };
      };
      /** @description Throttled (`throttled`, with `details.retry_after`). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  auth_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenObtainPairRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation or parse error (`validation_error`, `parse_error`). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Missing, invalid or expired credentials (`not_authenticated`, `authentication_failed`). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Throttled (`throttled`, with `details.retry_after`). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  auth_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["RefreshTokenRequest"];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation or parse error (`validation_error`, `parse_error`). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Missing, invalid or expired credentials (`not_authenticated`, `authentication_failed`). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Throttled (`throttled`, with `details.retry_after`). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  auth_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Missing, invalid or expired credentials (`not_authenticated`, `authentication_failed`). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Throttled (`throttled`, with `details.retry_after`). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  auth_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["RefreshTokenRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation or parse error (`validation_error`, `parse_error`). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Missing, invalid or expired credentials (`not_authenticated`, `authentication_failed`). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Throttled (`throttled`, with `details.retry_after`). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  clients_list: {
    parameters: {
      query?: {
        /**
         * @description `false` (default) hides archived clients, `true` shows only archived ones, `all` shows both.
         *
         *     * `false` - false
         *     * `true` - true
         *     * `all` - all
         */
        archived?: "false" | "true" | "all";
        /** @description Which field to use when ordering the results. */
        ordering?: string;
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        page_size?: number;
        /** @description A search term. */
        search?: string;
        /**
         * @description Only clients with this status. `archived` implies `archived=true` unless `archived` is given.
         *
         *     * `active` - Active
         *     * `archived` - Archived
         */
        status?: "active" | "archived";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedClientList"];
        };
      };
      /** @description Validation or parse error (`validation_error`, `parse_error`). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Missing, invalid or expired credentials (`not_authenticated`, `authentication_failed`). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Not allowed (`permission_denied`). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Throttled (`throttled`, with `details.retry_after`). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  clients_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClientRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Client"];
        };
      };
      /** @description Validation or parse error (`validation_error`, `parse_error`). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Missing, invalid or expired credentials (`not_authenticated`, `authentication_failed`). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Not allowed (`permission_denied`). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Throttled (`throttled`, with `details.retry_after`). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  clients_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this client. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Client"];
        };
      };
      /** @description Missing, invalid or expired credentials (`not_authenticated`, `authentication_failed`). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Not allowed (`permission_denied`). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Not found (`not_found`). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Throttled (`throttled`, with `details.retry_after`). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  clients_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this client. */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClientRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Client"];
        };
      };
      /** @description Validation or parse error (`validation_error`, `parse_error`). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Missing, invalid or expired credentials (`not_authenticated`, `authentication_failed`). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Not allowed (`permission_denied`). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Not found (`not_found`). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Throttled (`throttled`, with `details.retry_after`). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  clients_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this client. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedClientRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Client"];
        };
      };
      /** @description Validation or parse error (`validation_error`, `parse_error`). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Missing, invalid or expired credentials (`not_authenticated`, `authentication_failed`). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Not allowed (`permission_denied`). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Not found (`not_found`). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Throttled (`throttled`, with `details.retry_after`). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  clients_archive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this client. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Client"];
        };
      };
      /** @description Missing, invalid or expired credentials (`not_authenticated`, `authentication_failed`). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Not allowed (`permission_denied`). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Not found (`not_found`). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Throttled (`throttled`, with `details.retry_after`). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  clients_restore: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this client. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Client"];
        };
      };
      /** @description Validation or parse error (`validation_error`, `parse_error`). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Missing, invalid or expired credentials (`not_authenticated`, `authentication_failed`). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Not allowed (`permission_denied`). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Not found (`not_found`). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Throttled (`throttled`, with `details.retry_after`). */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  health_live: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  health_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Readiness"];
        };
      };
      /** @description Unexpected server error (`internal_error`). */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description At least one check failed. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Readiness"];
        };
      };
    };
  };
}
