# Generated by Django 5.2.17 on 2026-10-06 12:42

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0002_postgres_current_profile_integrity"),
        ("companies", "0002_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sales_hiring", "Sales hiring"),
                            ("bd_hiring", "Business development hiring"),
                            ("commercial_hiring", "Commercial hiring"),
                            ("partnerships_hiring", "Partnerships hiring"),
                            ("headcount_growth", "Headcount growth"),
                            ("commercial_team_growth", "Commercial team growth"),
                            ("funding", "Funding"),
                            ("market_expansion", "Market expansion"),
                            ("new_leadership", "New leadership"),
                            ("new_office", "New office"),
                            ("new_product", "New product"),
                            ("major_partnership", "Major partnership"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("evidence", models.TextField(help_text="Quoted or summarized from the source.")),
                (
                    "event_date",
                    models.DateField(help_text="When the event happened, as the source states it."),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When we found it."
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Null: no freshness rule applied yet (counts as fresh).",
                        null=True,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("schema_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signals",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signals",
                        to="companies.datasource",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        help_text="The earlier signal this row corrects or replaces.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="research.signal",
                    ),
                ),
            ],
            options={
                "ordering": ("-event_date", "-detected_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["company", "expires_at"], name="rs_signal_company_expiry_idx"
                    ),
                    models.Index(fields=["client"], name="rs_signal_client_idx"),
                    models.Index(fields=["data_source"], name="rs_signal_source_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "type__in",
                                [
                                    "sales_hiring",
                                    "bd_hiring",
                                    "commercial_hiring",
                                    "partnerships_hiring",
                                    "headcount_growth",
                                    "commercial_team_growth",
                                    "funding",
                                    "market_expansion",
                                    "new_leadership",
                                    "new_office",
                                    "new_product",
                                    "major_partnership",
                                    "other",
                                ],
                            )
                        ),
                        name="research_signal_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("evidence", ""), _negated=True),
                        name="research_signal_evidence_not_empty",
                    ),
                ],
            },
        ),
    ]
