# Generated by Django 5.2.17 on 2026-10-06 15:00

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_client_membership"),
        ("companies", "0002_contact"),
        ("research", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ICPAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "fit",
                    models.CharField(
                        choices=[("strong", "Strong"), ("medium", "Medium"), ("weak", "Weak")],
                        max_length=8,
                    ),
                ),
                (
                    "reasons",
                    apps.core.fields.StringListField(
                        blank=True, default=list, help_text="Why this fit, in plain words."
                    ),
                ),
                (
                    "concerns",
                    apps.core.fields.StringListField(
                        blank=True, default=list, help_text="Doubts or risks. May be empty."
                    ),
                ),
                ("raw_output", models.JSONField(blank=True, default=dict)),
                ("model_name", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=50)),
                ("schema_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "campaign_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="icp_assessments",
                        to="campaigns.campaignprofile",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="icp_assessments",
                        to="companies.company",
                    ),
                ),
                (
                    "company_research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="icp_assessments",
                        to="companies.companyresearch",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("add", "Add"), ("hold", "Hold"), ("skip", "Skip")], max_length=8
                    ),
                ),
                ("explanation", models.TextField()),
                ("raw_output", models.JSONField(blank=True, default=dict)),
                ("model_name", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=50)),
                ("schema_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_recommendations",
                        to="companies.company",
                    ),
                ),
                (
                    "icp_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="research.icpassessment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="HumanDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("add", "Add"), ("hold", "Hold"), ("skip", "Skip")], max_length=8
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="human_decisions",
                        to="research.airecommendation",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="human_decisions",
                        to="companies.company",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-decided_at", "-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["company", "-decided_at", "-created_at", "-id"],
                        name="rs_decision_latest_idx",
                    ),
                    models.Index(fields=["client"], name="rs_decision_client_idx"),
                    models.Index(fields=["ai_recommendation"], name="rs_decision_airec_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("decision__in", ["add", "hold", "skip"])),
                        name="research_humandecision_decision_valid",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="icpassessment",
            index=models.Index(fields=["company", "-created_at", "-id"], name="rs_icp_latest_idx"),
        ),
        migrations.AddIndex(
            model_name="icpassessment",
            index=models.Index(fields=["client"], name="rs_icp_client_idx"),
        ),
        migrations.AddIndex(
            model_name="icpassessment",
            index=models.Index(fields=["campaign_profile"], name="rs_icp_profile_idx"),
        ),
        migrations.AddIndex(
            model_name="icpassessment",
            index=models.Index(fields=["company_research"], name="rs_icp_research_idx"),
        ),
        migrations.AddConstraint(
            model_name="icpassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(("fit__in", ["strong", "medium", "weak"])),
                name="research_icpassessment_fit_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="icpassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("model_name", ""), _negated=True),
                    models.Q(("prompt_version", ""), _negated=True),
                    models.Q(("schema_version", ""), _negated=True),
                ),
                name="research_icpassessment_versions_set",
            ),
        ),
        migrations.AddIndex(
            model_name="airecommendation",
            index=models.Index(
                fields=["company", "-created_at", "-id"], name="rs_airec_latest_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airecommendation",
            index=models.Index(fields=["client"], name="rs_airec_client_idx"),
        ),
        migrations.AddIndex(
            model_name="airecommendation",
            index=models.Index(fields=["icp_assessment"], name="rs_airec_assessment_idx"),
        ),
        migrations.AddConstraint(
            model_name="airecommendation",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["add", "hold", "skip"])),
                name="research_airecommendation_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="airecommendation",
            constraint=models.CheckConstraint(
                condition=models.Q(("explanation", ""), _negated=True),
                name="research_airecommendation_explained",
            ),
        ),
        migrations.AddConstraint(
            model_name="airecommendation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("model_name", ""), _negated=True),
                    models.Q(("prompt_version", ""), _negated=True),
                    models.Q(("schema_version", ""), _negated=True),
                ),
                name="research_airecommendation_versions_set",
            ),
        ),
    ]
