# Generated by Django 5.2.17 on 2026-10-06 15:07

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0003_client_membership"),
        ("companies", "0002_contact"),
        ("research", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AngleSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="angle_links",
                        to="research.signal",
                    ),
                ),
            ],
            options={
                "db_table": "outreach_angle_signals",
            },
        ),
        migrations.CreateModel(
            name="AngleSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="angle_links",
                        to="companies.datasource",
                    ),
                ),
            ],
            options={
                "db_table": "outreach_angle_sources",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("call", "Call"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "language",
                    models.CharField(help_text="Code from the campaign languages.", max_length=16),
                ),
                ("subject", models.CharField(blank=True, help_text="Email only.", max_length=300)),
                ("body", models.TextField()),
                ("is_followup", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("exported", "Exported"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("exported_at", models.DateTimeField(blank=True, null=True)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("schema_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="companies.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="companies.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        help_text="The earlier message this row edits.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="outreach.message",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="MessageSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signal_links",
                        to="outreach.message",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_links",
                        to="research.signal",
                    ),
                ),
            ],
            options={
                "db_table": "outreach_message_signals",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="signals",
            field=models.ManyToManyField(
                blank=True,
                related_name="messages",
                through="outreach.MessageSignal",
                to="research.signal",
            ),
        ),
        migrations.CreateModel(
            name="MessageSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_links",
                        to="companies.datasource",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_links",
                        to="outreach.message",
                    ),
                ),
            ],
            options={
                "db_table": "outreach_message_sources",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="data_sources",
            field=models.ManyToManyField(
                blank=True,
                related_name="messages",
                through="outreach.MessageSource",
                to="companies.datasource",
            ),
        ),
        migrations.CreateModel(
            name="OutreachAngle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("angle", models.TextField()),
                (
                    "rationale",
                    models.TextField(help_text='The "because..." shown to the reviewer.'),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                ("schema_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outreach_angles",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_sources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="outreach_angles",
                        through="outreach.AngleSource",
                        to="companies.datasource",
                    ),
                ),
                (
                    "signals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="outreach_angles",
                        through="outreach.AngleSignal",
                        to="research.signal",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="message",
            name="angle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages",
                to="outreach.outreachangle",
            ),
        ),
        migrations.AddField(
            model_name="anglesource",
            name="angle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_links",
                to="outreach.outreachangle",
            ),
        ),
        migrations.AddField(
            model_name="anglesignal",
            name="angle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signal_links",
                to="outreach.outreachangle",
            ),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("researched", "Researched"),
                            ("recommended", "Recommended"),
                            ("decided", "Decided"),
                            ("contacted", "Contacted"),
                            ("replied", "Replied"),
                            ("meeting_booked", "Meeting booked"),
                            ("exported", "Exported"),
                            ("feedback", "Feedback"),
                        ],
                        max_length=24,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When it happened."
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["company", "-created_at"], name="out_activity_company_idx"
                    ),
                    models.Index(
                        fields=["campaign", "type", "-created_at"], name="out_activity_campaign_idx"
                    ),
                    models.Index(fields=["client"], name="out_activity_client_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "type__in",
                                [
                                    "researched",
                                    "recommended",
                                    "decided",
                                    "contacted",
                                    "replied",
                                    "meeting_booked",
                                    "exported",
                                    "feedback",
                                ],
                            )
                        ),
                        name="outreach_activity_type_valid",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="messagesignal",
            index=models.Index(fields=["signal"], name="out_msgsig_signal_idx"),
        ),
        migrations.AddConstraint(
            model_name="messagesignal",
            constraint=models.UniqueConstraint(
                fields=("message", "signal"), name="outreach_messagesignal_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="messagesource",
            index=models.Index(fields=["data_source"], name="out_msgsrc_source_idx"),
        ),
        migrations.AddConstraint(
            model_name="messagesource",
            constraint=models.UniqueConstraint(
                fields=("message", "data_source"), name="outreach_messagesource_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="outreachangle",
            index=models.Index(fields=["company", "-created_at"], name="out_angle_company_idx"),
        ),
        migrations.AddIndex(
            model_name="outreachangle",
            index=models.Index(fields=["client"], name="out_angle_client_idx"),
        ),
        migrations.AddConstraint(
            model_name="outreachangle",
            constraint=models.CheckConstraint(
                condition=models.Q(("angle", ""), _negated=True),
                name="outreach_angle_text_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="outreachangle",
            constraint=models.CheckConstraint(
                condition=models.Q(("rationale", ""), _negated=True),
                name="outreach_angle_rationale_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["company", "status"], name="out_message_company_status_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["angle"], name="out_message_angle_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["contact"], name="out_message_contact_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["client"], name="out_message_client_idx"),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel__in", ["linkedin", "email", "whatsapp", "call"])),
                name="outreach_message_channel_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "approved", "exported"])),
                name="outreach_message_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "draft"), ("approved_by__isnull", False), _connector="OR"
                ),
                name="outreach_message_approved_needs_approver",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "draft"), ("approved_at__isnull", False), _connector="OR"
                ),
                name="outreach_message_approved_needs_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "exported"), _negated=True),
                    ("exported_at__isnull", False),
                    _connector="OR",
                ),
                name="outreach_message_exported_needs_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel", "email"), ("subject", ""), _connector="OR"),
                name="outreach_message_subject_email_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("body", ""), _negated=True),
                name="outreach_message_body_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("language", ""), _negated=True),
                name="outreach_message_language_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="anglesource",
            index=models.Index(fields=["data_source"], name="out_anglesrc_source_idx"),
        ),
        migrations.AddConstraint(
            model_name="anglesource",
            constraint=models.UniqueConstraint(
                fields=("angle", "data_source"), name="outreach_anglesource_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="anglesignal",
            index=models.Index(fields=["signal"], name="out_anglesig_signal_idx"),
        ),
        migrations.AddConstraint(
            model_name="anglesignal",
            constraint=models.UniqueConstraint(
                fields=("angle", "signal"), name="outreach_anglesignal_unique"
            ),
        ),
    ]
