# Generated by Django 5.2.17 on 2026-10-06 12:26

import uuid

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_postgres_current_profile_integrity"),
        ("core", "0003_q_stats_cache_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("archive", "Archive"),
                            ("restore", "Restore"),
                            ("delete", "Delete"),
                        ],
                        max_length=16,
                    ),
                ),
                ("object_type", models.CharField(max_length=64)),
                ("object_id", models.UUIDField()),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="campaigns.client",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        help_text="A job type registered in code (`@tracked_job`), not free input.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partially succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("done_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, help_text="Runs started so far."),
                ),
                ("error_summary", models.TextField(blank=True)),
                (
                    "queue_task_id",
                    models.CharField(blank=True, help_text="Django-Q2 task id.", max_length=64),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="JobItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject_type", models.CharField(max_length=64)),
                ("subject_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Small JSON outcome, optional.", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="core.job",
                    ),
                ),
            ],
            options={
                "ordering": ("job_id", "created_at"),
            },
        ),
        # BackgroundJob (issue #25) is retired, not migrated: it had no client, which every Job
        # must carry, and the dev database holds no production data. Job replaces it behind the
        # same apps.core.jobs helpers. Rows of a database that matters would need a client first.
        migrations.DeleteModel(
            name="BackgroundJob",
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["object_type", "object_id", "-created_at"], name="core_audit_object"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["client", "-created_at"], name="core_audit_client"),
        ),
        migrations.AddConstraint(
            model_name="auditlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("action__in", ["create", "update", "archive", "restore", "delete"])
                ),
                name="core_auditlog_action_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["campaign", "-created_at"], name="core_job_campaign_created"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status"], name="core_job_status"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["client", "-created_at"], name="core_job_client_created"),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["queued", "running", "succeeded", "partial", "failed"])
                ),
                name="core_job_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "done_count__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("total_count"), "-", models.F("failed_count")
                        ),
                    )
                ),
                name="core_job_counts_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("finished_at__isnull", False),
                        ("status__in", ["failed", "partial", "succeeded"]),
                    ),
                    models.Q(
                        models.Q(("status__in", ["failed", "partial", "succeeded"]), _negated=True),
                        ("finished_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="core_job_finished_matches_status",
            ),
        ),
        migrations.AddIndex(
            model_name="jobitem",
            index=models.Index(fields=["job", "status"], name="core_jobitem_job_status"),
        ),
        migrations.AddConstraint(
            model_name="jobitem",
            constraint=models.UniqueConstraint(
                fields=("job", "subject_type", "subject_id"), name="core_jobitem_subject_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["queued", "running", "succeeded", "failed"])),
                name="core_jobitem_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("finished_at__isnull", False), ("status__in", ["failed", "succeeded"])
                    ),
                    models.Q(
                        models.Q(("status__in", ["failed", "succeeded"]), _negated=True),
                        ("finished_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="core_jobitem_finished_matches_status",
            ),
        ),
    ]
