"""Shared building blocks for the Django admin (issue #54). Rules: ``docs/admin.md``.

* ``ReadOnlyAdmin`` / ``ReadOnlyInline``: view only. Use for every append-only record and for
  anything that must change through a service (so the audit trail and the invariants hold).
* ``SuperuserOnlyMixin``: hides a model from staff who are not superusers (accounts, tokens,
  the task queue, memberships).
* ``mask_email``: what staff without the superuser flag see instead of a contact's address.

Access to the admin itself is ``User.is_staff`` (``AdminSite.has_permission``). Client roles
(``ClientMembership``) never grant it, and staff see only the models their Django model
permissions allow (superusers see everything).
"""

from __future__ import annotations

from typing import Any

from django.contrib import admin
from django.http import HttpRequest

#: Concrete models that are deliberately NOT in the admin, with the reason. Every other model in
#: the app registry must be registered: ``tests/test_admin.py`` fails for a new model that is in
#: neither place. Add a model here only with a reason that a reviewer can accept.
ADMIN_EXCLUDED_MODELS: dict[str, str] = {
    "auth.Permission": "Managed through groups and users; the rows are generated by migrations.",
    "contenttypes.ContentType": "Framework bookkeeping, nothing to inspect.",
    "sessions.Session": "Session keys are credentials; never shown.",
    "django_q.Task": "Base table of the Success and Failure proxies, which are registered.",
    "django_q.OrmQ": "Queued payloads (signed, pickled arguments); look at Job rows instead.",
}


def is_superuser(request: HttpRequest | None) -> bool:
    """True for an active superuser. Tolerates a request with no user (tests, scripts)."""
    user = getattr(request, "user", None)
    return bool(user and getattr(user, "is_active", False) and getattr(user, "is_superuser", False))


def mask_email(email: str) -> str:
    """``jane.doe@example.com`` becomes ``j***@example.com``; a blank stays blank."""
    if not email:
        return ""
    local, _, domain = email.partition("@")
    if not domain:
        return "***"
    return f"{local[:1]}***@{domain}"


class SuperuserOnlyMixin:
    """Every permission needs the superuser flag, on top of whatever the base class requires.

    Put it first in the bases: ``class FooAdmin(SuperuserOnlyMixin, admin.ModelAdmin)``.
    """

    def has_module_permission(self, request: HttpRequest) -> bool:
        return is_superuser(request) and bool(super().has_module_permission(request))  # type: ignore[misc]

    def has_view_permission(self, request: HttpRequest, obj: Any = None) -> bool:
        return is_superuser(request) and bool(super().has_view_permission(request, obj))  # type: ignore[misc]

    def has_add_permission(self, request: HttpRequest, *args: Any) -> bool:
        return is_superuser(request) and bool(super().has_add_permission(request, *args))  # type: ignore[misc]

    def has_change_permission(self, request: HttpRequest, obj: Any = None) -> bool:
        return is_superuser(request) and bool(super().has_change_permission(request, obj))  # type: ignore[misc]

    def has_delete_permission(self, request: HttpRequest, obj: Any = None) -> bool:
        return is_superuser(request) and bool(super().has_delete_permission(request, obj))  # type: ignore[misc]


class ReadOnlyAdmin(admin.ModelAdmin):  # type: ignore[type-arg]
    """No add, change or delete for anyone (superusers included); every field is read only."""

    def get_readonly_fields(self, request: HttpRequest, obj: Any = None) -> tuple[str, ...]:
        return tuple(f.name for f in self.model._meta.fields)

    def has_add_permission(self, request: HttpRequest, *args: Any) -> bool:
        return False

    def has_change_permission(self, request: HttpRequest, obj: Any = None) -> bool:
        return False

    def has_delete_permission(self, request: HttpRequest, obj: Any = None) -> bool:
        return False


class ReadOnlyInline(admin.TabularInline):  # type: ignore[type-arg]
    """A view-only inline: nothing can be added, edited or removed through it."""

    extra = 0
    can_delete = False
    show_change_link = True

    def has_add_permission(self, request: HttpRequest, obj: Any = None) -> bool:
        return False

    def has_change_permission(self, request: HttpRequest, obj: Any = None) -> bool:
        return False

    def has_delete_permission(self, request: HttpRequest, obj: Any = None) -> bool:
        return False
