"""The data model docs must match the models (issue #54).

* The ER diagram, entity index and field reference are generated by
  ``python manage.py print_schema --write``; this test fails when they are stale.
* Every model has an entity section in ``docs/data-model.md`` (or is covered by another one),
  and that section names every allowed value of the model's enum columns, so a new enum value
  cannot be added without the page saying so.
* Docs are linked from the READMEs.

Skipped when the repository docs are not available (for example inside the backend image).
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from django.core.management import call_command

from apps.core import schema_doc

MODEL_DOC = schema_doc.MODEL_DOC
REFERENCE_DOC = schema_doc.REFERENCE_DOC
REPO_ROOT = schema_doc.REPO_ROOT

pytestmark = pytest.mark.skipif(
    not MODEL_DOC.exists() or not REFERENCE_DOC.exists(),
    reason="repository docs are not available (e.g. inside the backend image)",
)

#: Models without a heading of their own, and the section that describes them.
COVERED_BY = {
    "AngleSignal": "OutreachAngle",
    "AngleSource": "OutreachAngle",
    "MessageSignal": "Message",
    "MessageSource": "Message",
}

STALE_HINT = "Run `python manage.py print_schema --write` from backend/ and commit the result."


def _sections(text: str) -> dict[str, str]:
    """``### Name`` sections of the page, keyed by the first word of the heading."""
    parts = re.split(r"^### ", text, flags=re.MULTILINE)[1:]
    out: dict[str, str] = {}
    for part in parts:
        heading, _, body = part.partition("\n")
        out[heading.split()[0]] = body.split("\n## ")[0]
    return out


@pytest.mark.parametrize("block", sorted(schema_doc.BLOCKS))
def test_generated_blocks_are_current(block: str) -> None:
    path = schema_doc.BLOCKS[block]
    current = schema_doc.extract_block(path.read_text(encoding="utf-8"), block)
    assert current is not None, f"{path.name} has no generated '{block}' block"
    assert current == schema_doc.render_blocks()[block], (
        f"The '{block}' block of {path.name} is out of date. {STALE_HINT}"
    )


def test_print_schema_write_is_idempotent() -> None:
    before = {p: p.read_text(encoding="utf-8") for p in set(schema_doc.BLOCKS.values())}
    call_command("print_schema", "--write")
    assert {p: p.read_text(encoding="utf-8") for p in before} == before, STALE_HINT


def test_every_local_model_is_in_the_index_and_has_a_section() -> None:
    text = MODEL_DOC.read_text(encoding="utf-8")
    index = schema_doc.extract_block(text, "index") or ""
    sections = _sections(text)
    for model in schema_doc.local_models():
        name = model.__name__
        assert f"| {name} |" in index, f"{name} is missing from the entity index. {STALE_HINT}"
        owner = COVERED_BY.get(name, name)
        assert owner in sections, (
            f"docs/data-model.md has no '### {owner}' section for {model._meta.label}: "
            "describe the new entity (what it is for, its rules) or add it to COVERED_BY."
        )


def test_entity_sections_name_every_enum_value() -> None:
    sections = _sections(MODEL_DOC.read_text(encoding="utf-8"))
    problems: list[str] = []
    for model in schema_doc.local_models():
        body = sections.get(model.__name__)
        if body is None:
            continue
        for field in model._meta.concrete_fields:
            if not field.choices:
                continue
            missing = [str(v) for v, _ in field.choices if f"`{v}`" not in body]
            if missing:
                problems.append(f"{model.__name__}.{field.name}: {missing}")
    assert not problems, "Enum values not named in their section of docs/data-model.md: " + str(
        problems
    )


def test_no_stale_planning_language_is_left() -> None:
    text = MODEL_DOC.read_text(encoding="utf-8")
    for phrase in ("draft for team sign-off", "Where the sibling issues", "see open question"):
        assert phrase not in text, f"stale text in data-model.md: {phrase!r}"


def test_docs_are_linked_from_the_readmes() -> None:
    root = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    docs_index = (REPO_ROOT / "docs" / "README.md").read_text(encoding="utf-8")
    for target in ("docs/data-model.md", "docs/permissions.md", "docs/admin.md"):
        assert target in root, f"README.md does not link {target}"
    for target in ("data-model.md", "data-model-reference.md", "permissions.md", "admin.md"):
        assert f"({target})" in docs_index, f"docs/README.md does not link {target}"
    for doc in ("admin.md", "data-model-reference.md"):
        assert (Path(REPO_ROOT) / "docs" / doc).exists()
