# Generated by Django 5.2.17 on 2026-10-06 10:21

import uuid

import django.db.models.functions.text
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",  # noqa: E501
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="email address"),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive users cannot log in or refresh tokens."
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Can sign in to the Django admin."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",  # noqa: E501
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ("email",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email", django.db.models.functions.text.Lower("email"))
                        ),
                        name="accounts_user_email_lowercase",
                    )
                ],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
