# Generated by Django 5.2.17 on 2026-10-06 12:18

import uuid

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0002_postgres_current_profile_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=300)),
                ("website", models.CharField(blank=True, help_text="As entered.", max_length=2000)),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Normalized, or null.",
                        max_length=253,
                        null=True,
                    ),
                ),
                ("profile_url", models.URLField(blank=True, max_length=2000)),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="ISO 3166-1 alpha-2, upper.", max_length=2
                    ),
                ),
                (
                    "input_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("csv", "CSV import"),
                            ("provider", "Provider"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("analyzing", "Analyzing"),
                            ("analyzed", "Analyzed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_by_job_id", models.UUIDField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ("name", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("provider", "Data provider"),
                            ("website", "Website"),
                            ("news", "News"),
                            ("manual", "Manual entry"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Provider name, site or publication, or who typed it.",
                        max_length=200,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Required unless type is manual or provider.",
                        max_length=2000,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        help_text="The provider's own record id (ADR 0002).",
                        max_length=200,
                    ),
                ),
                ("retrieved_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "evidence_date",
                    models.DateField(
                        blank=True, help_text="Date stated by the source itself, if any.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-retrieved_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="CompanyResearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("researched_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("industry", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("headquarters", models.CharField(blank=True, max_length=300, null=True)),
                ("employee_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "business_model",
                    models.TextField(blank=True, help_text="Free text, as found.", null=True),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("b2b", "B2B"),
                            ("b2c", "B2C"),
                            ("both", "B2B and B2C"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("products_services", models.TextField(blank=True, null=True)),
                ("target_customers", models.TextField(blank=True, null=True)),
                ("sales_headcount", models.PositiveIntegerField(blank=True, null=True)),
                ("bd_headcount", models.PositiveIntegerField(blank=True, null=True)),
                ("marketing_headcount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "commercial_partnerships_headcount",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "department_growth",
                    models.JSONField(
                        blank=True, help_text="Free-form, where the provider gives it.", null=True
                    ),
                ),
                (
                    "headcount_change_3m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percent, -12% is -12.00.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "headcount_change_6m",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "headcount_change_12m",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research",
                        to="companies.company",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_research",
                        to="companies.datasource",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "company research",
                "ordering": ("-researched_at", "-created_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["client", "domain"], name="co_company_client_domain_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["campaign", "status"], name="co_company_camp_status_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["campaign", "archived_at"], name="co_company_camp_arch_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                django.db.models.functions.text.Lower("name"),
                models.F("campaign"),
                name="co_company_camp_lname_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=models.Q(("domain__isnull", False)),
                fields=("campaign", "domain"),
                name="companies_company_domain_unique_per_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "analyzing", "analyzed", "failed"])),
                name="companies_company_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_source__in", ["manual", "csv", "provider"])),
                name="companies_company_input_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="companies_company_name_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["client", "-retrieved_at"], name="co_ds_client_retrieved_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="datasource",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["provider", "website", "news", "manual"])),
                name="companies_datasource_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="datasource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type__in", ["manual", "provider"]),
                    models.Q(("url", ""), _negated=True),
                    _connector="OR",
                ),
                name="companies_datasource_url_required",
            ),
        ),
        migrations.AddIndex(
            model_name="companyresearch",
            index=models.Index(
                fields=["company", "-researched_at", "-created_at", "-id"],
                name="co_research_latest_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companyresearch",
            index=models.Index(fields=["client"], name="co_research_client_idx"),
        ),
        migrations.AddIndex(
            model_name="companyresearch",
            index=models.Index(fields=["data_source"], name="co_research_source_idx"),
        ),
        migrations.AddConstraint(
            model_name="companyresearch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("classification__isnull", True),
                    ("classification__in", ["b2b", "b2c", "both", "unknown"]),
                    _connector="OR",
                ),
                name="companies_research_classification_valid",
            ),
        ),
    ]
