# Generated by Django 5.2.17 on 2026-10-06 12:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_postgres_current_profile_integrity"),
        ("companies", "0001_company_research_data_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=300)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("profile_url", models.URLField(blank=True, max_length=2000)),
                ("email", models.EmailField(blank=True, max_length=320)),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("not_found", "Not found"),
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                            ("invalid", "Invalid"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "relevance_reason",
                    models.TextField(blank=True, help_text="Why this person (Brief section 15)."),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(blank=True, help_text="1 is best.", null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("erased_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to="companies.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ("rank", "name", "id"),
                "indexes": [
                    models.Index(fields=["client"], name="co_contact_client_idx"),
                    models.Index(
                        fields=["company", "archived_at"], name="co_contact_company_arch_idx"
                    ),
                    models.Index(fields=["data_source"], name="co_contact_source_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("archived_at__isnull", True), ("role__in", ["primary", "secondary"])
                        ),
                        fields=("company", "role"),
                        name="companies_contact_one_primary_secondary",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            models.Q(("profile_url", ""), _negated=True),
                            ("archived_at__isnull", True),
                        ),
                        fields=("company", "profile_url"),
                        name="companies_contact_profile_url_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["primary", "secondary", "none"])),
                        name="companies_contact_role_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "email_status__in",
                                ["unknown", "not_found", "unverified", "verified", "invalid"],
                            )
                        ),
                        name="companies_contact_email_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="companies_contact_name_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rank__isnull", True), ("rank__gte", 1), _connector="OR"
                        ),
                        name="companies_contact_rank_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("email", ""), _negated=True),
                            ("email_status__in", ["unknown", "not_found"]),
                            _connector="OR",
                        ),
                        name="companies_contact_status_needs_email",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email", ""),
                            models.Q(("email_status", "not_found"), _negated=True),
                            _connector="OR",
                        ),
                        name="companies_contact_not_found_no_email",
                    ),
                ],
            },
        ),
    ]
