# Generated by Django 5.2.17 on 2026-10-07 11:43

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0003_client_membership"),
        ("companies", "0002_contact"),
        ("core", "0004_job_jobitem_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("csv", "CSV import"),
                            ("provider", "Provider"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("partial", "Partially completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "file_size",
                    models.PositiveBigIntegerField(blank=True, help_text="Bytes.", null=True),
                ),
                (
                    "file_sha256",
                    models.CharField(blank=True, help_text="Hex digest, CSV only.", max_length=64),
                ),
                ("column_mapping", models.JSONField(blank=True, default=dict)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("restored_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="core.job",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "import batches",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(blank=True, max_length=300)),
                ("website", models.CharField(blank=True, max_length=2000)),
                ("domain", models.CharField(blank=True, max_length=253, null=True)),
                ("profile_url", models.CharField(blank=True, max_length=2000)),
                ("country", models.CharField(blank=True, max_length=2)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("duplicate", "Duplicate"),
                            ("restored", "Restored"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rows",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="campaigns.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_rows",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("batch_id", "row_number"),
            },
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["campaign", "-created_at"], name="imp_batch_campaign_created"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["client", "-created_at"], name="imp_batch_client_created"),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["status"], name="imp_batch_status"),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["campaign", "file_sha256"], name="imp_batch_campaign_sha"),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["pending", "processing", "completed", "partial", "failed", "cancelled"],
                    )
                ),
                name="imports_batch_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["manual", "csv", "provider"])),
                name="imports_batch_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_count__gte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("created_count"), "+", models.F("duplicate_count")
                                    ),
                                    "+",
                                    models.F("restored_count"),
                                ),
                                "+",
                                models.F("skipped_count"),
                            ),
                            "+",
                            models.F("failed_count"),
                        ),
                    )
                ),
                name="imports_batch_counts_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source", "csv"), _negated=True),
                    models.Q(("file_sha256", ""), _negated=True),
                    _connector="OR",
                ),
                name="imports_batch_csv_has_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("finished_at__isnull", False),
                        ("status__in", ["cancelled", "completed", "failed", "partial"]),
                    ),
                    models.Q(
                        models.Q(
                            ("status__in", ["cancelled", "completed", "failed", "partial"]),
                            _negated=True,
                        ),
                        ("finished_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="imports_batch_finished_matches_status",
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(
                fields=["batch", "outcome", "row_number"], name="imp_row_batch_outcome"
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(fields=["company"], name="imp_row_company"),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(fields=["client"], name="imp_row_client"),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"), name="imports_row_number_unique_per_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outcome__in", ["created", "duplicate", "restored", "skipped", "failed"])
                ),
                name="imports_row_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_number__gte", 1)), name="imports_row_number_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("outcome__in", ["created", "duplicate", "restored"]), _negated=True),
                    ("company__isnull", False),
                    _connector="OR",
                ),
                name="imports_row_company_for_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("outcome", "failed"), _negated=True),
                    models.Q(("error_code", ""), _negated=True),
                    _connector="OR",
                ),
                name="imports_row_failed_has_code",
            ),
        ),
    ]
