# Generated by Django 5.2.17 on 2026-10-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_client_membership"),
        ("companies", "0004_company_duplicate_constraints"),
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importrow",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "The matched company: the existing one (strong) or the possible duplicate."
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="importrow",
            name="match_strength",
            field=models.CharField(
                blank=True,
                choices=[("strong", "Strong"), ("weak", "Weak")],
                help_text="strong: linked to an existing company; weak: created and flagged.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="importrow",
            name="matched_on",
            field=models.CharField(
                blank=True, help_text="domain, profile or name_country.", max_length=16
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("candidate__isnull", True), ("match_strength", ""), ("matched_on", "")
                    ),
                    models.Q(
                        ("match_strength__in", ["strong", "weak"]),
                        models.Q(("matched_on", ""), _negated=True),
                        ("candidate__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="imports_row_match_complete",
            ),
        ),
    ]
